### ISSUE TITLE
Alteração na estrutura do site da receita

### ISSUE THREAD

**Issue by hamorim** [gbazilio/nfebrasil#1]
Mestre, 

Antes de tudo, obrigado pelo esforço na criação da API. Tentei usar  a mesma, mas tive como retorno na requisição do captcha. 

"No captcha image found on target URL http://www.nfe.fazenda.gov.br/portal/consulta.aspx?tipoConsulta=completa&tipoConteudo=XbSeqxE8pl8= when trying to search for element ctl00_ContentPlaceHolder1_imgCaptcha."

O código vai conseguir abrir? poderia tentar contribuir na solução.

Abraços.

**Comment by gbazilio** [comment]
@hamorim
Vou abrir o código sim, com certeza. Amanhã ou sábado vou subir. Sua ajuda seria mto boa kra. : ) 

Obrigado pelo feedback. Talvez minha última modificação tenha quebrado a API ou o site da receita realmente mudou.

**Comment by gbazilio** [comment]
@hamorim , **resolvido**. Site da receita não modificou. Problema estava no código. Erro de digitação que os testes não pegaram. =(

**Comment by hamorim** [comment]
Obrigado!!!
